name: Stats

on: push

env:
  RAILS_ENV: test
  RUBY_VERSION: "2.7.2"
  NODE_VERSION: "12.19.0"

jobs:
  style_lint:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{ env.RUBY_VERSION }}"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - uses: actions/cache@v2
        name: Cache Bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        name: Cache Yarn dependencies
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs=4 --retry=3
          yarn install
      - name: Rubocop
        run: |
          bundle exec rubocop
      - name: TSLint
        run: |
          yarn lint
      - name: Brakeman
        run: |
          bundle exec brakeman
  # unit_tests:
  #   name: Unit tests
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:11-alpine
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #     redis:
  #       image: redis:4.0.6
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Set up Ruby
  #       uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: "${{ env.RUBY_VERSION }}"
  #     - uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: "${{ env.NODE_VERSION }}"
  #     - uses: actions/cache@v2
  #       name: Cache Bundler dependencies
  #       with:
  #         path: vendor/bundle
  #         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gems-
  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "::set-output name=dir::$(yarn cache dir)"
  #     - uses: actions/cache@v2
  #       name: Cache Yarn dependencies
  #       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get -yqq install libpq-dev
  #         gem install bundler
  #         bundle config path vendor/bundle
  #         bundle install --jobs=4 --retry=3
  #         yarn install
  #     # - name: Set up database
  #     #   run: |
  #     #     cp config/database.yml.ci config/database.yml
  #     #     bundle exec rails db:create
  #     #     bundle exec rails db:schema:load
  #     #   env:
  #     #     RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  #     - name: Increase watchers
  #       run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  #     - name: Run Ruby tests
  #       run: |
  #         bundle exec rails test
  #       env:
  #         RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  #     - name: Run Javascript tests
  #       run: |
  #         yarn test
  # assets_precompile:
  #   name: Precompile assets
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:11-alpine
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #     redis:
  #       image: redis:4.0.6
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Set up Ruby
  #       uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: "${{ env.RUBY_VERSION }}"
  #     - uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: "${{ env.NODE_VERSION }}"
  #     - uses: actions/cache@v2
  #       name: Cache Bundler dependencies
  #       with:
  #         path: vendor/bundle
  #         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gems-
  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "::set-output name=dir::$(yarn cache dir)"
  #     - uses: actions/cache@v2
  #       name: Cache Yarn dependencies
  #       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get -yqq install libpq-dev
  #         gem install bundler
  #         bundle config path vendor/bundle
  #         bundle install --jobs=4 --retry=3
  #         yarn install
  #     # - name: Set up database
  #     #   run: |
  #     #     cp config/database.yml.ci config/database.yml
  #     #     bundle exec rails db:create
  #     #     bundle exec rails db:schema:load
  #     #   env:
  #     #     RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  #     - name: Increase watchers
  #       run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  #     - name: Precompile assets
  #       run: |
  #         bundle exec rails assets:precompile
  #       env:
  #         RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
